# version format
version: 1.0.0-prerelease.{build}
before_build:
- appveyor-retry dotnet restore -v Minimal
init:
- ps: $Env:prerelease = "prerelease." + $Env:APPVEYOR_BUILD_NUMBER
build_script:
- dotnet build "src\DavisVantage.WeatherReader" --no-dependencies --version-suffix %prerelease%
test_script:
- dotnet test "test\DavisVantage.WeatherReader.Tests"
cache:
- '%USERPROFILE%\.nuget\packages'